export const projects = [
  { id: 1, title: 'E-Commerce Platform', tag: 'Web App', href: '/projects/e-commerce' },
  { id: 2, title: 'Mobile Fitness Tracker', tag: 'iOS/Android', href: '/projects/fitness' },
  { id: 3, title: 'Dashboard Analytics', tag: 'Data Viz', href: '/projects/analytics' },
  { id: 4, title: 'Portfolio Website', tag: 'Creative', href: '/projects/portfolio' },
  { id: 5, title: 'Restaurant Booking', tag: 'Service', href: '/projects/booking' },
  { id: 6, title: 'Social Media Tool', tag: 'SaaS', href: 'https://example.com', target: '_blank' },
  { id: 7, title: 'Learning Platform', tag: 'EdTech', href: '/projects/learning' },
  { id: 8, title: 'Real Estate App', tag: 'PropTech', href: '/projects/real-estate' },
  { id: 9, title: 'Music Streaming', tag: 'Media', href: '/projects/music' },
  { id: 10, title: 'Task Manager', tag: 'Productivity', href: '/projects/tasks' },
  { id: 11, title: 'Travel Guide', tag: 'Mobile', href: '/projects/travel' },
  { id: 12, title: 'AI Chatbot', tag: 'ML/AI', href: '/projects/chatbot' },
  // { id: 13, title: 'Video Editor', tag: 'Creative Tools' },
  // { id: 14, title: 'Crypto Wallet', tag: 'FinTech' },
  // { id: 15, title: 'Gaming Platform', tag: 'Entertainment' },
  // { id: 16, title: 'Health Monitor', tag: 'HealthTech' },
  // { id: 17, title: 'Supply Chain', tag: 'Logistics' },
  // { id: 18, title: 'CRM System', tag: 'Business' },
  // { id: 19, title: 'Blog Platform', tag: 'Publishing' },
  // { id: 20, title: 'Event Planner', tag: 'Events' },
  // { id: 21, title: 'Recipe Finder', tag: 'Food' },
  // { id: 22, title: 'Car Rental', tag: 'Transport' },
  // { id: 23, title: 'Fashion Store', tag: 'Retail' },
  // { id: 24, title: 'Smart Home', tag: 'IoT' },
];
